version: '3.8'

services:
  domains_api:
    build: .
    command: [ "/bin/domains_api" ]
    ports:
      - "5000:5000"
    env_file:
      - .env.domains

  nuclei_scanner:
    build: .
    command: [ "/bin/nuclei_scanner" ]
    env_file:
      - .env.nuclei