version: '3.8'

# TODO: Fix the env issues 
services:
  domains_api:
    build: .
    command: [ "/bin/domains_api" ]
    ports:
      - "3000:3000"
    env_file:
      - .env.domains

  nuclei_scanner:
    build: .
    command: [ "/bin/nuclei_scanner" ]
    env_file:
      - .env.nuclei
