version: '3.8'

services:
  artefact-api:
    build:
      context: ./artefact-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - api-network
  
  domains-api:
    build:
      context: ./domains-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
