version: '3.8'

# TODO: Fix the env issues 
services:
  domains_api:
    build: .
    command: ["/bin/domains_api"]
    ports:
      - "3000:3000"
    env_file:
      - ./.env.domains
    

  # artefacts_api:
  #   build: .
  #   command: ["/app/artefacts_api/main"]
  #   ports:
  #     - "3001:3000"

  # nuclei_scanner:
  #   build: .
  #   command: ["/app/nuclei_scanner/main"]
  #   ports:
  #     - "3002:3000"
