services:
  domains_api:
    image: 897729130899.dkr.ecr.ap-southeast-1.amazonaws.com/cybertrap-backend:domains-api-v0.1.13
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/bin/domains_api" ]
    ports:
      - "5000:5000"
    env_file:
      - .env.domains

  nuclei_scanner:
    image: 897729130899.dkr.ecr.ap-southeast-1.amazonaws.com/cybertrap-backend:nuclei-scanner-v0.2.2
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/bin/nuclei_scanner" ]
    env_file:
      - .env.nuclei

  schedule_scan_service:
    image: 897729130899.dkr.ecr.ap-southeast-1.amazonaws.com/cybertrap-backend:schedule-scan-service-v0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/bin/scan_scheduler" ]
    env_file:
      - .env.scheduler
    profiles:
      - donotstart

