apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cybertrap-cluster
  region: ap-southeast-1

managedNodeGroups:
  - name: arm64-nodes-xlarge
    instanceType: t4g.xlarge  # Changed to t4g.xlarge for a larger ARM64 instance
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    privateNetworking: true
    labels:
      lifecycle: ec2-autoscaler
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true