---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    uri: AgCp4oarf9nzc93laZcInWLnyQ+zpuBjwIo0ITMu85MpVqZTt73s9LGN4R58Xk5cO8ngeRxx7h0j1rDnDfrZeIPP/G/XV9YHdBZjtLdxVfOPjJgg17PYpXQofiF34cyd9LVa0EYz/q24Pu59cEhMZ+HNbLLPYOT4WNmVIVPQpoXYiFH8VpRhyNeIAj3tKJM3w0mH3ZOZZkkchydZwWoGbSPfhMZStZnPe0uYFaTb4sPrMI92ukuKHvrW2M1JvbOT7foEXjmM0ObruZZjZ+75XBP3yxlsXfB+u4jgHI2mPhFqns+1+dfxPgyJibO0r8tfWEAtqsZpYvFcQppiUTOw9cd1Vc8vn9h96lgldVW1VnrVyQauEMthk76brvTWK/yJgATRf88Bg6yYBhmx+tYRhHVme0cTfCHUmf5UDr1PJk97Inf2z3YJjDXaNlPyO29h7IyFUQKOO2Qt8IT30Sh1p1v/Q6vBAdJqt7EByq7PTnS4ImsXgXSOBRNTS+RML+UI/c6CrdYL/n31ecHp5UOVzU0Vak963X8EtD8mfnMWoZDMYb+WVQaJaB2z2ChfAOYsP7kvhOJh+iOEPCXXxbG+H9JVySMCV9A68AsVRHQvXBR3JucnGDKB9/jCoXDA8ZAqWhSqX9mjie+Pef0Z6ntDfO8NbIsNbfKy61NaSpZP2aYWspqG6LnE3nP9oHHcCxsHARx/Yn25fBL43pK72pogyw0D4RePd2ZK0JmKH77aYCI645FQ79beSv4yrPmxfsk3TzOL+IkNk2HAkSWYq5oDbsAUzLMkBKeir6MK1pOI24LhXt+wvb8Ro8e2Biswn6HMD/VqZeorzjj65lfi6w8szCWs
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    uri: AgCLFN7X4WBBxHW+f63ApBW8PiTgkyq7MFg8q8sQ76+ywQuzTLLydp7xAWn53rpC/WK8DNEptwVHjcj9Dev30vxse7HodPZXdHXhkc8gjYtrYcNLlP9MO30j3Ils7wZndIHp3qoeGZYhQ1olDFhFB158YgwwoBT4UPBtkQCCy2+nbERE6g/jFzL2viHgAKNyVWUoYiZ/et7l7LoD2mbT7Kww6wo0OkQY6G5dm5m5dLR642XtpKhUh59pBHlekCSFOcjVVpoi/9XyyAJwv4MqG8d02brDF0LupmJQ8fYymvEz5Ra/woPgeXZncam4tnDIaSZ4gWvoNpqo68NmN6NmU+ZcyursP57R6io4arJ1CO1s3pY0bWpDLnvngi7dzJCPGcmyD39I4WmrAlkThrlmFkIQI8s3ECG7R2PYasD+SQdUklVcpFZQlHBohVeh9/pgTQTehYuMO8Rsp+RU3R78P1unLc1gmQamavy1a71H529D2YbGMUWvTeQkvFb4X2Xt+2jRYTLzxDtL6a5cPzagi57tP2urKfaUuDzoeB8NU/T4g3in4/vHWNB39SH9hjz1RrrBDG/Ed02RiJPmtvibZhh7Rj4mrA+jZDQq9a3xiewbSugmQebzvImEoSMh9jO55rd01QgsImKvzokHPS42eRfC62mgS690sHSgKskalwrtqkU+eW+RJEmtkJhZ8y7pj7RXxGbFJ2FjSY1gvrdnQtlKmReSq8S4mRnhLRs4OLwTYWR8gZJ4lRo+sVXh1RRl2oXDVPOGDlH7a4VXvZ8AM6E2qoRHfV6saQU3max/5LFp2LwPHF5cEwu6A5Odlm7bZWmwq189pqQ7A0nGFHJva47pxQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    access-key-id: AgAv7NPU/vS8i9d9LK5LUhjYaUe1ZO5WftzNoyPRCoYp4wne5P/rc8NeE1os6RpauC3wCnzq48Kx9+xJJ/igZSLM5uyYqWsHmW4LajKgf8dBvp79LPwIF9JfOIy+m65Pz3FaIoGbZfoiXoC4tc8tX2qWpR/f/6aOf2kv+ojjdMJX899UGoE33Zy2E5uX4TSpl4qOiK9iR/MXDzoByCFeiCetCumRAXOUcazTUtpeWiKNlUYDJy/UGAcbLvbk5nxTfezu2CVKicD/Z+JzFoWkPjlwfQ5FGiCyj2D0Dg9ipvEIiNvppsJPMB9KYynKB5nqElEXc6S+lsRxhonimkW7qRPxNgLgFttk98cRmWhrNBy2jyQqI6HCWo3Ggy1a5lO7MyzJi4N6ZFHRkY8ax+xR+a81JzgE33v1QF0/JbimAjuFX1bmTOIWAsKAmJt7IyiTIRCVVAgy+fywujp73DRu+WFr5SDcg9ZECAmb4G3b+UPHocIOkgKbFHtiXri1UJ2Vx0m0IXTiUOKzlKfZ7iudLJKBUBsJ8C6VQZnZxjWpbebBdMhcI5OqbraAYyG/A2JlVutrHRmVGrjNpFx4luZPkwBn4LGnY651VsDg0IpgW5mIQFNK9YqoPWKpgvNU4iyqGIklQysZSBozrFbzy8ki4sE0PUiVb0ZnL+UNhupPQ3COlDPebZKLCUpljzPxMwzXrCS2p9rJr+km3FCDZrafdjU0tWfpow==
    secret-access-key: AgBJQa8InIF12uzPuAfxiTgV9Rcq/y+jLWYJwtLvVAVwsy8cW51p46z5HwPO2X9Ncvi3dIFBNQCTJVfK6gB3D07gY79c+XYJbZ4L5KSXgM6B9tg+NDuxOT0DmLEK4UXKpPOjIieFXdtIS+EnTiyDruHPcBQ6uGZSHRgXaL0H1xqSgEWH4opng2g7IkUhwi3ez6YhLvbsbB2GVx72FR30Fv6JP313ggTQCqHpHL7YrC3i7Zk0iPHf2H/JxUBeWcJ+8X/y+ekfSE7E/8F+0eEoWnwawsM31slg1SLNWbMVw+KoUWLaEkd5rQh/2TifGif/CpOZ3KKH7Pev/+eJk73jTh8Cti1nOlgT3/7+oJAZxnnZ2kfXpgRCB9Pse5cUr9J1q2Yme2I6yhGXLaqGuSCK75pLSOAMmJxLzswf7XNeTTnlOsNhbWBdjCwHNctG9cjrpJsaHYgVCl4+hHfDgBXRwqlMKFrVLcFKlgFY4+EN3OW+uHdGSZHpoL9AMRDbKOzB7QYVSjFwwew5GH/pLz2yua2zUHw2BFHK6IH49FF79cdrK60tAr8PIeX1gFKBHqPA/Z18tJYzpVwMMZ0IfW4VWv9NKTkbAir4Udv2Qo5+tLckXw8ywSNr8d/q9AZbh0z4h/lk6vFEhT8P3+Xg2mVff4Jv07KK8LeqjBCQ2j7dDpPRAA2ezTXGaSnFPqfZL6f8d3RsxPSYgt4k0btbckOC4//JsnEoOwJrcuAVT1g6BUluY9XNbj4L8FXf
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaque
