---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    uri: AgAVNflwuPyAM9RaHIx9afub5f52UH209SF3EaOevSuDn2FKdSZbki36pIntJXWl4iOghoiF39x7fsRfR93XcWPBwqWwaTNIl340/yKIHlPrcku5TmHBMMd4i1BUEvxZ1lcQaU71U49SMGqKB494aonzMr785QkwBvV1Ux72w0nHk7oEopp4Mc5t9+rCKRi8sf+NW5g942fK3GybkaSva1itShIGE6kQ3Yk5X4vDN6b88E+IRFO0RI0VYcEZvEDAmMdlyyId6xJIr2TKb5e2nFwiUc1BQbDKEGvINC02ehbWF6d/IZpwbdRt8i0VKcN4le+8kl5B0/1a/me5vr67o0Mr8frF2ikJSba/ySR6spwoPwWohEbHAMavAt3Zo2uRfAlvlf7CsmI05LpeMTiDJgaPNc0dD/p0szXt/Nb6h4aAfcaDTj7mMZ7ZlEGXd67tFcgTWyhbP5neijt0H7hlzlA7+4ZdTU9mnGS2OMkiYA9AAGura6V8LS5B2Qqcr40wZZevMHflWyin4v5eHBm1GXY2NiUY9U8sLMwPJ7b//hrNAKxZAXLJKuW+7YnmHcFcSJjgJwmFEbP5uhXLxgQIqKZ6YJuy6Ms20KIlZmTqvH/84zr/mnEpLBA4slL/VbRhAOvmWDF15a7Lc6uQEXAH0ECN1ja3MzRAKUzhuoyTApReni7ZslSGNU+u9t6MZ7lu01XhZboVB2U8vlIGOCaGQonw+Wb5VUKOfpocKVV43dL3r9LOemIwZXlOM7llrZVRnCf4Juxw70nmLYieVjc+XGCT5GLwxvRz6gzCrQxpMMq3ZIE3mTsVQ5Y1M8gE6EYUvqZO5kiwZMSo/iVrWN/TfCLw
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    uri: AgCMyO/1gfuZ0OWkMkRl9qG6LrfGU49tz5SBo1XsV5VkCl3rcZZROot6kfGcKS4OFG5eNWvSaG3uvZuLfbIzwHsdSXDUF3BbEXrsX9F3fbuAtGgOiyrk0ipgXaoWntw2Z34Ci1pJKbjsbJt9V0ntece6B/UPvDtgnEtnSWEJiwrAexTKTeuH0iSxtuRY6mwc9W7pCpKnCY43lR9iyKeoUJQDZKI9s56zhi+SO0qDW+lvJJQqZ9B0T3/RTGYURojxV7DMTIpa4L88hG610af2wcb2uTsAU3JS4frGVYSU2qjs7SOzlEqKev4Q8ERqAPSy8xgMjVOtcYej4WXZgjKoLgPpDJauUxr01cntkoW2ib0y/mhaiGqR8HftsZz/HLUaQo2MnVgqUr+QmHklbEsylAZ7fRKA2Tl09Eu0pGTkZcH2HugmR3quma+o3W+onIgrwbYnmyFOiI5jOyAMB9rh1OBqFaQLTGifxg0fgoB2IFpann5NObUjkoZKhS4O86PkzCOL041wsATECm4cH/PBF/bYB0mnbq4+7C7vfyQR+sXShCw1qf750MsPJENqHIIiq7AcjlWydEYE5CJSz2PAjjJPsJrAHssaGQGuN9cPc3iPvQONs2GV5gpNXWfsNQbnC6fIWVKOPLVuQlABLf4brqdwco0+300Bja+gfiP2OPVeOu1Ei88aXn4SPHJiAh/OZEuo+4+r
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    access-key-id: AgAYhjFc8Amx+0xS8wTcb/Jslq8OeQw7GWurS+JpHozl2e7ezqNLCDR3qVUVGvOf+8Hz7CgnsrZu75WCBiApbcBhDJDsSoiLig402ioOHi+cOkCSDbEcB1Ktr6fIVTOGgWR2PeQAWi8BxUh2mRMEUmqEVzwNHKRU/YFhcmJRbrbu5aebkpwtZlYNaajme1SCOIQKTPhDzy/mfzdHdniFgqASFPRi2tlY6B+7NT385HSGKTzVCxI+j1Zbi9us1MVX5JHkjIyNXZuV/gED3LdgYw8eKTyK2DGHoACgeGVn2DSSMsgwdtqPZ54P5PRsqYxmbXbI9fxsd7XoYE1Z210Rrm10FKaU+Yq9ZLWY+fj1g2tLqOTPt+8TK0t2Xnpm/RpsSA6ZL6Pyf2/LfOWSWsIGxpSk436VKGsidCRkah9ZSOOJFEj0SUMMdfeJ7wuFDWtx3rEUwTE3eATrNI1DnHrwatRONwIQTYphOxMAe0AFmRna4iwr8MfibOxHz5StBfchFHgXeV6MRMBV5PfGr9Vm0pmLgqoeO0d+ehkASCUbQ6rXaj4QvvZZttrfblB8gHsvOCkhiZ+YuHCJ4TrImqnTRIfJb83rs6EI2a68x8I+GWU8QjEK9PfjpQU9nFJWZkt6+TVhCE9c7OcO9AiJX89rsKiUxNQGaNrIup3h26FMGdpj/BIrCcWwTgDyqktP9srG3WG41uQkTykHifXbYRxXsghX/HSHhQ==
    secret-access-key: AgC4RpLNR4Rw9zFoWPB2kmErcxjcyNKMpjEuTdxGI2uUitE5dZlYl6cPr0xBQSyVd5y8ixG9PymquJYy1/UpmdkZl78khloDCHC+51HtB/shOz7JBfGxImK1uPHp4TKbhlxeQrMg2oyg5ZbmrmqLhn5tQxdrOcYjbap2rDDKkq1n+flSvd217kL9qkqAyNRY56cWdSPcV8/M1alWxSrnmhhHzi0ju1+j8T9Vn7iN53lK54EWemgZvg4PTcEp8GXlDMBcN+P9XLLfh+4eswbhSreURrzTQ2vhhLlO9I4B1vbJRM+ituENgo0thImOUGn3zs+25wx4F70nhr23Gy60vOtf2djGpy2zbpplVA2npCSwNGmc1ODHm7JXAaba7+BTCID4WB0X4KxxM82CJRBolelGTWntfcCgGPK6Ikz+InnJEXJuazdCx4f0m747IcPB27eejUFxfi6P41x2H7YjmgdGUITnJbybbYKkh9DzkDgzTH+Xl/8O9LD9n2DKmE/nLHPzJj6FYkwLgr9DkyV9UaV7PZmlo1dEwtUocdlRwW5M6ETg4nssR40DOp6vjM9IdhvZ49lLBossZV0J8q54PMOP2+1pIbSYs2fQ8uYtpYa5skDcNQBgi5bsScmVOkrOKeyfR3luLBhHpV6tODAfdEfG0Fq1mkxdx0aG+ybKjAaX5eS5OaOX+m/W2puofd+xtD/2pry5Cyrbptt4tL9quTnDGbAvfDi/b93nkE17JgzZhxCyi/tnihW3
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaque
