---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    uri: AgC1lfl78hk9owM66fojRReoTMmhrzHrh0FicOKbwDWN6MLefxw6PlXWGz/HvNlL2Wug26hkDwPYvqXzN2WKHmAmE+ZjcEzziHbXMTohcsJuPknsM4BCSulS76XvYVpFO7p9GqeTntP0K0ZgLIZYpdXfTPtK/2KhlboUdEFV8oEk03tesiPDL9HwwzYDdlvQmwpqxHWMbYOcmcu0sNndSrcC5Lx58J3IfRJsfXRa2GQKMuqHhZPjOs6qA+qNZjD8OnXpiyLT4M12rKcQTd/fRCulAABIsq1PXPuDafAT7qyDcaDADdBjnrdJ94GZIMwB+VoS3ptaFEJIkW5w11SB2M3jN4HLywgQ7qhuJThthK2UsWq2CyI7Zep9CWvv+a2oaXkEv51Nmz32bFoImmDyOnbiKc44sWz1A8D1niAcpyK1CoSBT7ojlP8v39RfWaJRnrrbQfk/wTgThx2L3+cjDKJSgQ6fQ5V4aJ9J/VwkOimQNiOFxlqBDm5yWwmA/0WGzdypUqOERXtPAf5Za6L1tJjltq5KE62sqaXO55An3oJmGvZFO9yVxUdbmRlT7jya4xvj7n3+RJZ45kV8y3r4DbGhtj/4vQofKKN+PuPcxtPBgDeSpNrZ03Bj16GjftICZqs7fFTc+qfm8sRAwEOjGSM9miyNDtZwRNmGcYZe8DmXoMdk/jenl1qBbStmtynQQQCDrRvlDAhu7KlStBgWU+iigv+6z3IrTZl8BRKM/R1yMAP8yMCvRTJb9osCXBNLcKdU7nwWu3W84jElWxSf4Rr0bvxlh7RBwMqo9cECBmigkBTkE0G6j9FJjv9UttcS/CPGZ5cLw5hvliccFoaPRoMw
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    uri: AgA/he1o9CuNKsLWcTRgunsAoJQmzDFDz8wzayXbkMeDLfPqQM4EjV3Pn+y1S5/RIOP/X9dvwarQ6l3YE7SamVneF53PgaxbmsVsFMiY8xs224yvr88zcb37mh6ksNnlrAxKYepWI8yR2mEtfAV2XhauzTCyA9tj1Opm8sl5uIKSRESXE9ZF8Q960D9PNvs30fWnMNQ/vD/+9YbYokKNkDGQSaZ6jpAg4NCDouHExFcKRhtQkPGr1JKIFNArI1ouZ5c1cZELuf1pVCW4W/wNjqzm12uOwrXhnFivc48qGkOm8Sn+X2ArCLAnKJiXDy0CSZ0hr6L9iq3vcVK3L1256X44EYeNKfLCIDnihNSd8ICO5x+c4OGlL8WFT8e1SePT5uyK8Xs83Jl/9L3mMzeK5vXJlJJvkzWtFC37oGbRKTaU9rrbMfClGjLz9dI+/L3hE/MhEzyswDyP252ufdQAn/jr3PlVBD4OoNDdUmFsDDucVe6Op+j0VNZfw30joz5VHOSBLgiUHDrXxeSKX2kq7vz0lHzhHh1SxvwqKvwzGKR8ou+wFgbEnJmggQ+cGsHa+bXlkm1uxAMdV53zM8693KHhdA8b08P8hQEr86q24NoEMlLCRFiLMTPLgXSfgDtQmJnkzqvU5X8diWIHLkF70zH2um0TPqcPuWRAVFA+XSOOZ4WWVVbbUjppOlE7l4AVCVqylVTPZibtcztfFylC/Qi8hUPyKkDhu+FNMuU7LKko8Fq787+oIIiS5m0cwuetDnIs9CQ5JRPESZczFWCm0gAWweoRv0uXEYrQ/mS3W0aascSae6wQ2/9LusjgD+M3nvzxWjrtBSTDXCmLnprr+9mZsQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    access-key-id: AgA2ReBf/P8di2rMlM8cGXH3foZGeJG52K1aN1PoUg96XgpErCxj3Nq/mWs4BH8AAFVDAO3Eiy8KwtdRCckxMWKAvFO0NI4ESjb8FyYBCzN9XRuEBPDNt1xR67LvP+fPao/jf7JAJN0hG5MTz7s8RRv/zeJ5nDRB05FEWR46O/fORZaDVs2Yx+hC8+IfK1s86jl+03aHPmBCU+mM4592Ogq+RlA7AmSxksomYpAZPZoHWEqWRfVt8tIzeuop7/7o76rO6KjBVgs6O4f9vpzR5mKArl/NqsgKMq9tk9emOaj7Gp3ASqQZia0ozsbGU2mx2WKkV42932w9wH8xvEEFfSc1dViivw2tikdyennJGYBbVrzRu21eA2Dxxri3Z4yLOz79yTlxRc0v1Gp8cEuR9DytX2iCVm6c4h0s46l7wxPGHy6vWEj9jG7gkieGJZ2PfttuzA1rVIKfhLDTQYIqrvxqwLmdjHPxS29DMpzIWGHTMZ5oFvSKmIvRZ5QDYduWK0376PiwS5sDVTrKE9F9oD+Qf7Pd71K1WiiuiATYCXEQOLNXMNZJU6Fq/is/zBETjkn14GR3mX6erU8HBfRyCudjxrNt/CSqw0ICJ5xdZORrWhPFNw1fAbpGqUkbi3zc18lTzJZ9bmjeoIH0hNcOT8Mm6OpNqUAoDEqumf67HruQJ3MJnB7t0rkhF1x1pC5PXHT/gI9yVgZmHalPxPURgL1eYsrYGQ==
    secret-access-key: AgBjAbBBK1w/M/iAPUbirCjoQjkh/ZBprJBzy67MF95+Gryh2r77tLxQBkAmRX+gxDUGDYEb/VUEh8X1+JWHQclk7/wqYsV4aaYw8CHJovdN7WJ6ir5av4JUIsGbDq9ozuI6Yj8MAsIwFosB8PbJwwBpfoG0yG5/KMFXiutGw+CWsH2A/lHyODFW3culY0DREpPbXHybBfhnRsUbk9EeP/UANohwNepRLYt1ubslKVlVKvFjR3hUtzgAw8Tjpd5z+7rAKDw0gNUeetv6rjlG/ZCsUFQUDIYn/Guc08jXXzpsCPYTuCa19iiAYIyRge441O08NjV3T/7MTNlgtr80yy4g/BIfY1y7ILkE2QpeFZ/eO5IujbLNtqKIZqnohDBKNdV+pfxSPFJSC6OqT7XVM7Kya/d0CuBYFg0boO58gixQemWAZYrmPAOYxVH33VpfgRriiFh10tuJuPMEC8YNPjCLhHoHN5YOf3GA5vB5Y6JTQ3FPLL8VcAUQJtHrRwtUUrIU9+PKe25BVxPiMCO8McynsTJZ8jIZnkruE+XQu46xzACGP78l4c2QacLcvs4POWTrhAQg8Ikn2NSsE51Hwl/ixZNGJtxTmJFf9sI7xo/LR5PBL2mIm5JCxrOZyhck3Wq7XTfhGo93Ecpn7pEv+CBFEw2z474Bqj7ixu7+/RAJV981oykK8dK0jPoBC4weTiJc91lV092olmc5DE28sfkVzSKK7LqA5UNFGrwOfWH/f6zigSq8XRf7
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaque
