apiVersion: batch/v1
kind: CronJob
metadata:
  name: clone-nuclei-templates
  namespace: default
spec:
  schedule: "0 0 * * *" # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clone-nuclei-templates
            image: alpine/git # Use a lightweight image with git
            command:
            - /bin/sh
            - -c
            - |
              if [ ! -d "/mnt/efs/nuclei-templates" ]; then
                git clone https://github.com/projectdiscovery/nuclei-templates /mnt/efs/nuclei-templates
              else
                cd /mnt/efs/nuclei-templates && git pull
              fi
            volumeMounts:
            - name: efs-volume
              mountPath: /mnt/efs
          restartPolicy: OnFailure
          volumes:
          - name: efs-volume
            persistentVolumeClaim:
              claimName: efs-pvc
